"""add option to make a quiz public

Revision ID: 0159d89cb96b
Revises: aab38be953e5
Create Date: 2022-04-20 10:40:58.904052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0159d89cb96b'
down_revision = 'aab38be953e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('public', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'public')
    # ### end Alembic commands ###
