"""add due dates to quizzes

Revision ID: 33e7b14673b9
Revises: 0159d89cb96b
Create Date: 2022-04-20 11:15:53.559230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e7b14673b9'
down_revision = '0159d89cb96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('due', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'due')
    # ### end Alembic commands ###
