"""add columns to instance answers table

Revision ID: fc67918b653c
Revises: 8d69d3fb7208
Create Date: 2022-04-21 17:25:43.902683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc67918b653c'
down_revision = '8d69d3fb7208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizinstanceanswers', sa.Column('answer_id', sa.Integer(), nullable=False))
    op.add_column('quizinstanceanswers', sa.Column('correct_answer_id', sa.Integer(), nullable=False))
    op.add_column('quizinstanceanswers', sa.Column('correct', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizinstanceanswers', 'correct')
    op.drop_column('quizinstanceanswers', 'correct_answer_id')
    op.drop_column('quizinstanceanswers', 'answer_id')
    # ### end Alembic commands ###
